#!/bin/bash

# opens a file in the editor of your choice
# good thing: it checks which editor is open and opens the file in that editor
# if no editor is found it defaults to a lightweight editor (like kwrite)

# the order in which to execute the commands
# breaks on success
# available are the following commands:
#
# kwrite_new_win
# quanta_new_win
# kate_new_win
#
# quanta_new_tab
# kate_new_tab
#
order=(
  kate_new_tab
  kwrite_new_win
)
# nothing should be changed below

# new kate tab
function kate_new_tab {
  isrunning kate || return 1
  echo "open file in a new kate tab:"
  kate -u "$1" --line "$2"
}
# new kate window
function kate_new_win {
  echo "open file in kate:"
  kate "$1"  --line "$2"
}
# new kwrite window
function kwrite_new_win {
  echo "open file in kwrite:"
  kwrite "$1"
}

# check if a process is running
function isrunning {
  pid=(`pidof $1`)
  return `[[ ${pid[0]} ]]`
}

# cached konqueror file
if [[ ${1#/tmp/kde} != $1 || ${1#/var/tmp/kdecache} != $1 ]]; then
#echo "cache" >> /home/milian/.bin/editorlog
  # cached file
  kwrite "$1"
  exit
fi

# call functions based on order defined above
oldname=$1
fname=$(echo $1 |  sed -e 's/^file:\///')
file=$(echo $fname | sed -e 's/:.*//g')
line=$(echo $fname | cut -d ':' -f2)

if [[ "$oldname" != "$fname" ]]; then
 file="file:/$file"
fi
if [[ "$line" = "$fname" ]]; then
 echo "WOOO"
 line=$2
fi

for i in `seq 1 ${#order[@]}`;
do
  ${order[$i-1]} "$file" "$line" $&& exit 0
done
